apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - trainingrecipes.yaml
  - trainingruns.yaml
  - anvils.yaml
  - trainingartifacts.yaml
  - evaluationruns.yaml
  - modelpromotions.yaml
